version: '3.8'
services:
  frontend:
    image: react-application-template:latest
    #image: ghcr.io/kostakoff/react-application-template:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - docker-compose-network

networks:
  docker-compose-network:
    ipam:
      config:
        - subnet: 172.16.16.0/24
