projectName: my
applicationName: front
appNamespace: applications
k8sCluster: dev-k8s.myltd.lab

replicas: 1
accountName: default

front:
  server:
    ingress:
      enabled: true
      class: internal-nginx
    url: front.apps.dev-k8s.myltd.lab
  logLevel: info
  resources:
    requests:
      memory: '128Mi'
      cpu: '100m'
    limits:
      memory: '256Mi'
      cpu: '200m'

images:
  pullSecret: 
  front:
    registry: ghcr.io
    repository: kostakoff
    imageName: react-application-template
    imageTag: latest
