name: Build CI

on:
  push:
    branches: [ "master" ]

# Jobs section
jobs:
  build-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/kostakoff/rocky-base-images:8-nodejs20-docker
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: npm build
        shell: bash
        run: |
          npm install
          npm run build
      - name: docker build nginx front container
        run: |
          docker build . --tag ghcr.io/kostakoff/react-application-template:latest
      - name: Push application docker container
        run: |
          docker push ghcr.io/kostakoff/react-application-template:latest
