apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: '{{ include "app.fullName" . }}'
      release: {{ .Release.Name | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        app: {{ include "app.fullName" . }}
        chart: {{ template "app.chart" . }}
        release: {{ .Release.Name | quote }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
{{- if .Values.images.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret }}
{{- end }}
      serviceAccountName: {{ .Values.accountName }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "app.fullName" . }}-nginx
        - name: service-cert-secret
          secret:
            defaultMode: 420
            secretName: {{ include "app.fullName" . }}-service-cert
## containers block
      containers:
      - name: nginx-front
        image: {{ include "front.image" . }}:{{ .Values.images.front.imageTag }}
        imagePullPolicy: Always
        command:
          - nginx
          - -g
          - daemon off;
        ports:
        - containerPort: 8443
          protocol: TCP
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 30
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            memory: '{{ .Values.front.resources.requests.memory }}'
            cpu: '{{ .Values.front.resources.requests.cpu }}'
          limits:
            memory: '{{ .Values.front.resources.limits.memory }}'
            cpu: '{{ .Values.front.resources.limits.cpu }}'
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: service-cert-secret
            mountPath: /etc/pki/private
